[package]
name = "relify-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Embedded DataFusion and Parquet implementation of Relify"
repository.workspace = true
publish = false

[lib]
name = "relify_local"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
arrow.workspace = true
arrow-ipc.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
datafusion.workspace = true
futures.workspace = true
object_store.workspace = true
parquet.workspace = true
parallite = { version = "0.1.0-rc.2", path = "../parallite" }
relify-catalog = { version = "0.1.0-rc.2", path = "../relify-catalog" }
relify-core = { version = "0.1.0-rc.2", path = "../relify-core" }
relify-index = { version = "0.1.0-rc.2", path = "../relify-index" }
relify-iceberg = { version = "0.1.0-rc.2", path = "../relify-iceberg" }
relify-kernels = { version = "0.1.0-rc.2", path = "../relify-kernels" }
relify-kmeans = { version = "0.1.0-rc.2", path = "../relify-kmeans" }
relify-meta = { version = "0.1.0-rc.2", path = "../relify-meta" }
relify-storage = { version = "0.1.0-rc.2", path = "../relify-storage" }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros"] }
