[package]
name = "parqdb-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
arrow.workspace = true
arrow-ipc.workspace = true
datafusion-python.workspace = true
futures.workspace = true
pyo3 = { workspace = true, features = ["abi3-py310", "extension-module"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
parqdb-catalog = { version = "0.2.0-rc.1", path = "../rust/parqdb-catalog" }
parqdb-core = { version = "0.2.0-rc.1", path = "../rust/parqdb-core" }
parqdb-index = { version = "0.2.0-rc.1", path = "../rust/parqdb-index" }
parqdb-local = { version = "0.2.0-rc.1", path = "../rust/parqdb-local" }
parqdb-meta = { version = "0.2.0-rc.1", path = "../rust/parqdb-meta" }
parqdb-storage = { version = "0.2.0-rc.1", path = "../rust/parqdb-storage" }
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true
